In [1]:
import pandas as pd 
from sqlalchemy import create_engine

In [2]:
engine = create_engine("postgresql://postgres:1152205@localhost:5432/olist")

In [3]:
tables = pd.read_sql("""SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' """,engine) 
tables

                          table_name
0                          customers
1                         gelocation
2                        order_items
3                     order_payments
4                             orders
5                      order_reviews
6                           products
7  product_category_name_translation
8                            sellers

In [4]:
customers = pd.read_sql("SELECT * FROM customers",engine)
gelocation = pd.read_sql("SELECT * FROM gelocation",engine)
order_items = pd.read_sql("SELECT * FROM order_items",engine)
order_payments = pd.read_sql("SELECT * FROM order_payments",engine)
orders = pd.read_sql("SELECT * FROM orders",engine)
order_reviews = pd.read_sql("SELECT * FROM order_reviews",engine)
products = pd.read_sql("SELECT * FROM products",engine)
product_category_name_translation = pd.read_sql("SELECT * FROM product_category_name_translation",engine)
sellers = pd.read_sql("SELECT * FROM sellers",engine)

In [5]:
print(f"customers = {customers.shape}")
print(f"gelocation = {gelocation.shape}")
print(f"order_items = {order_items.shape}")
print(f"order_payments = {order_payments.shape}")
print(f"orders = {orders.shape}")
print(f"order_reviews  = {order_reviews .shape}")
print(f"products = {products.shape}")
print(f"product_category_name_translation  = {product_category_name_translation .shape}")
print(f"sellers  = {sellers .shape}")

customers = (99441, 5)
gelocation = (1000163, 5)
order_items = (112650, 7)
order_payments = (103886, 5)
orders = (99441, 8)
order_reviews  = (99224, 7)
products = (32951, 9)
product_category_name_translation  = (71, 2)
sellers  = (3095, 4)

In [6]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [7]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [8]:
gelocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [13]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [14]:
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [15]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [16]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [17]:
product_category_name_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [18]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [19]:
orders.columns , order_items.columns , order_payments.columns

(Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
        'order_approved_at', 'order_delivered_carrier_date',
        'order_delivered_customer_date', 'order_estimated_delivery_date'],
       dtype='str'),
 Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
        'shipping_limit_date', 'price', 'freight_value'],
       dtype='str'),
 Index(['order_id', 'payment_sequential', 'payment_type',
        'payment_installments', 'payment_value'],
       dtype='str'))

In [20]:
items_agg = order_items.groupby("order_id").agg(
total_items=("order_item_id","count"),
total_price=("price","sum"),
total_freight_value=("freight_value","sum")).reset_index()

items_agg.head()

,order_id,total_items,total_price,total_freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,199.90,18.14

In [21]:
payment_agg=order_payments.groupby("order_id").agg(
    total_payment=("payment_value","sum"),
    max_installments=("payment_installments","max"),
    payment_count=("payment_sequential","count")).reset_index()

payment_agg.head()

,order_id,total_payment,max_installments,payment_count
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,2,1
1,00018f77f2f0320c557190d7a144bdd3,259.83,3,1
2,000229ec398224ef6ca0657da4fc703e,216.87,5,1
3,00024acbcdf0a6daa1e931b038114c75,25.78,2,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,3,1

In [22]:
ML_table = orders.merge(
    items_agg,on="order_id",
    how="left"
)
ML_table.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_items,total_price,total_freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,19.90,8.72

In [23]:
ML_table= ML_table.merge(
    payment_agg,on="order_id",
    how="left"
)
ML_table.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_items,total_price,total_freight_value,total_payment,max_installments,payment_count
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,29.99,8.72,38.71,1.0,3.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,118.70,22.76,141.46,1.0,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,159.90,19.22,179.12,3.0,1.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,45.00,27.20,72.20,1.0,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,19.90,8.72,28.62,1.0,1.0

In [24]:
ML_table["order_id"].is_unique

True

In [25]:
ML_table.shape

(99441, 14)

In [26]:
ML_table.to_csv("ML_table.csv",index=False)

In [27]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\m
['.antigravity', '.cache', '.docker', '.gemini', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.jupyter', '.lesshst', '.n8n', '.nuget', '.python_history', '.vscode', '.vscode-shared', 'ansel', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'CrossDevice', 'Desktop', 'Documents', 'Downloads', 'dvc-project', 'Favorites', 'IntelGraphicsProfiles', 'Links', 'Local Settings', 'Microsoft', 'ML_project', 'ML_table.csv', 'My Documents', 'NetHood', 'Notebook1_Data_Preparation.ipynb', 'Notebook2_Create_Labels.ipynb', 'Notebook3_Train_Validation_Test_Split.ipynb', 'Notebook4_EDA (the detailed one).ipynb', 'Notebook5_Feature engineering.ipynb', 'Notebook6_Train, tune, evaluate.ipynb', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{49585583-1248-11f0-8317-c12ecc0fcc2f}.TM.blf', 'NTUSER.DAT{49585583-1248-11f0-8317-c12ecc0fcc2f}.TM.blf.cnpf', 'NTUSER.DAT{49585583-1248-11f0-8317-c12ecc0fcc2f}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{49585583-1248-11f0-8317-c12ecc0fcc2f}.TMContainer00000000000000000001.regtrans-ms.cnpf', 'NTUSER.DAT{49585583-1248-11f0-8317-c12ecc0fcc2f}.TMContainer00000000000000000002.regtrans-ms', 'NTUSER.DAT{49585583-1248-11f0-8317-c12ecc0fcc2f}.TMContainer00000000000000000002.regtrans-ms.cnpf', 'ntuser.ini', 'OneDrive', 'PrintHood', 'Rana_delver.db', 'Rana_delver.sqbpro', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates']